name: mather
description: library extention for language dart an base type (List)
version: 1.0.2
repository: https://github.com/ScorlyFly/Mather

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
